version: "3.3"
services:
  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: NeuralDriveDB
    ports:
      - 5432:5432

  