export const Action = {
  START_SESSION: 'START_SESSION',
  CONNECT_WATCH: 'CONNECT_WATCH',
  RECEIVE_DATA_WATCH: 'RECEIVE_DATA_WATCH',
  EXECUTE_QUERY: 'EXECUTE_QUERY',
  GET_WATCH_DATA: 'GET_WATCH_DATA',
  SAVE_SESSION_LOCAL: 'SAVE_SESSION_LOCAL',
  DELETE_SESSION: 'DELETE_SESSION',
  GET_SESSION_BY_ID: 'GET_SESSION_BY_ID',
};

export const Status = {
  IDLE: 3,
  STOP: 0,
  START: 1,
};

export const ERROR_CODE = {
  FAIL_CONNECT_TO_SERVER: -1,
};
