export const Action = {
  START_SESSION: "START_SESSION",
  RECEIVE_DATA_WATCH: "RECEIVE_DATA_WATCH",
  EXECUTE_QUERY: "EXECUTE_QUERY",
  GET_VIZUALIZATIONS: "GET_VIZUALIZATIONS",
};

export const Status = {
  IDLE: 3,
  STOP: 0,
  START: 1,
};

export const ERROR_CODE = {
  FAIL_CONNECT_TO_SERVER: -1,
};
